version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mysite
hooks:
  AfterInstall:
    - location: scripts/install-deps.sh
  ApplicationStart:
    - location: scripts/start.sh
      runas: root